apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omnigtm.fullname" . }}
  labels:
    {{- include "omnigtm.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
