{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "omnigtm.fullname" . }}
  labels:
    {{- include "omnigtm.labels" . | nindent 4 }}
    {{- with .Values.monitoring.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "omnigtm.apiSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.interval | default "15s" }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout | default "10s" }}
{{- end }}
