apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnigtm.fullname" . }}
  labels:
    {{- include "omnigtm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "omnigtm.apiSelectorLabels" . | nindent 4 }}
